### Get all Todo items
GET http://localhost:5289/api/todo
Accept: application/json

###

### Create a new Todo item
POST http://localhost:5289/api/todo
Content-Type: application/json

"This is a test for the  new structure"